name: Javadoc CI

on:
  push:
    branches:
      - master

permissions: 
  contents: write
jobs:
  javadoc:
    if: ${{ github.repository_owner == 'tr7zw' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - name: Build with Maven
      run: mvn package
    - name: Copy artifacts
      shell: bash
      run: |
        mkdir -p artifacts/v2-api && cp -r item-nbt-api/target/reports/apidocs/* artifacts/v2-api
        mkdir -p artifacts/v2-plugin && cp -r item-nbt-plugin/target/apidocs/* artifacts/v2-plugin
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        clean: false
        folder: artifacts
